name: Run tests
on: push

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        id: repository-checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        id: node-setup
        uses: actions/setup-node@v4
        with:
          node-version: lts
      
      - name: Install dependencies
        id: install-dependencies
        run: npm ci

      - name: Run tests
        id: run-tests
        run: npm run test
      
      - name: Run checks
        id: run-checks
        run: npm run check
